apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
  labels:
    app: tito
type: Opaque
data:
  mysql-password: VGl0bzIwMTY=
  # Password created like this:
  # Linux  echo -n 'Tito2016' | base64
  # powershell "[convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes(\"Tito2016\"))"